### PR TITLE
Modify for better use with module-loading

### PR DESCRIPTION
**Pull request by marciaga**
I installed the library via npm but wasn't able to register the directive in the usual way with Vue, so I modified the package to be friendlier to use as an imported module and easier to register as a global directive in a app with separated-out components (a la vue-loader). Thanks for making this library!

-Mark

### CODE REVIEW

**Comment by james2doyle** [comment]
Hey this is cool. But does it still work with browsers?

**Comment by marciaga** [comment]
It doesn't, you're right. Let me see if I can offer the best of both worlds. I'll update the pull request in a bit

**Comment by marciaga** [comment]
@james2doyle Updated!

**Comment by james2doyle** [comment]
OK cool. You tested this in the browser as well?

**Comment by marciaga** [comment]
Yeah, I just fired up the example from this repo in Chrome and it's working exactly as it should

**Comment by james2doyle** [comment]
OK great

**Pull request merged**
