### PR TITLE
Vue 2.0 Initial compatibility

### PR DESCRIPTION
**Pull request by drolean**
I'm doing a upgrade to use in vue 2.0.1

the list working fine, but have some items to revised

### CODE REVIEW

**Comment by james2doyle** [comment]
Can you pull in the latest version? someone submitted a PR that fixed some bugs

**Comment by james2doyle** [comment]
Also, why remove the image example?

**Comment by drolean** [comment]
Retorned image example. fixed some itens

**Comment by drolean** [comment]
i dont understand the droppable features! can you explain??

**Comment by james2doyle** [comment]
Maybe @Jerret321 can explain more precisely?

**Comment by Jerret321** [comment]
@drolean draggable or droppable futures means that users can set one element draggable or droppable like jquery ui [draggable](http://jqueryui.com/draggable/) or [droppable](http://jqueryui.com/droppable/).

**Pull request closed without merging**
