### PR TITLE
Fixed the directive's conflicting prop names

### LINKED ISSUE #3: Warnings on directives in 1.0.16
Hey, great plugin, it's been super useful! One thing I've noticed is that as of the version of Vue I'm using (1.0.16, development version) console warnings will show for each element that uses a directive on page load. For example if you swap in Vue ```1.0.16``` into the example file you get:

```
vue.js:990 [Vue warn]: Failed to resolve directive: drop
vue.js:990 [Vue warn]: Failed to resolve directive: drag-end
vue.js:990 [Vue warn]: Failed to resolve directive: drag-leave
vue.js:990 [Vue warn]: Failed to resolve directive: drag-enter
vue.js:990 [Vue warn]: Failed to resolve directive: drag-over
vue.js:990 [Vue warn]: Failed to resolve directive: drag-start
vue.js:990 [Vue warn]: Failed to resolve directive: drop
```

This doesn't affect functionality, but can get annoying with large numbers of objects and directives.

### PR DESCRIPTION
**Pull request by hamstu**
Closes #3.

:+1:

### CODE REVIEW

**Comment by james2doyle** [comment]
Nice! Can you also bump the package.json version?

**Comment by hamstu** [comment]
Oh good catch; done!

**Comment by james2doyle** [comment]
Should the README.md also be updated? https://github.com/hamstu/vue-drag-and-drop#usage

**Comment by hamstu** [comment]
@james2doyle I did. But you reminded me to update the example code, so I made another PR. :ok_hand:

**Pull request merged**
